import type { ObjectNode, ObjectField, ASTNode } from '../types';

/**
 * Parse language class/struct definitions back into an AST.
 * Uses regex-based extraction — works for typical class definitions
 * generated by BeanTrans or hand-written simple classes.
 */

// ─── Java Parser ───────────────────────────────────────────────

export function parseJavaToAST(source: string): ObjectNode {
  const classes = splitJavaClasses(source);
  if (classes.length === 0) {
    throw new Error('No Java class found in input.');
  }
  // Build a map of className → ObjectNode
  const nodeMap = new Map<string, ObjectNode>();
  for (const cls of classes) {
    const node = parseJavaClass(cls);
    nodeMap.set(node.name, node);
  }
  // Resolve nested references
  for (const node of nodeMap.values()) {
    for (const field of node.fields) {
      if (field.node.kind === 'string') {
        const resolved = resolveTypeRef(field.node, nodeMap);
        if (resolved) field.node = resolved;
      }
    }
  }
  return nodeMap.values().next().value!;
}

function splitJavaClasses(source: string): string[] {
  const results: string[] = [];
  const regex = /(?:@\w+\s*\n\s*)*(?:public\s+)?class\s+\w+\s*\{[^}]*\}/g;
  let match;
  while ((match = regex.exec(source)) !== null) {
    results.push(match[0]);
  }
  if (results.length === 0 && source.trim()) results.push(source);
  return results;
}

function parseJavaClass(cls: string): ObjectNode {
  const nameMatch = cls.match(/class\s+(\w+)/);
  const name = nameMatch ? nameMatch[1] : 'Root';

  const fields: ObjectField[] = [];
  // Match fields like: private String name; or public int age;
  const fieldRegex = /(?:private|public|protected)\s+([\w<>\[\]?,\s]+?)\s+(\w+)\s*;/g;
  let m;
  while ((m = fieldRegex.exec(cls)) !== null) {
    const javaType = m[1].trim();
    const fieldName = m[2];
    fields.push({
      name: fieldName,
      node: javaTypeToNode(javaType),
      nullable: false,
    });
  }
  return { kind: 'object', name, fields };
}

function javaTypeToNode(type: string): ASTNode {
  const t = type.trim();
  if (t === 'String') return { kind: 'string' };
  if (t === 'int' || t === 'Integer' || t === 'long' || t === 'Long')
    return { kind: 'number', isFloat: false };
  if (t === 'float' || t === 'Float' || t === 'double' || t === 'Double' || t === 'BigDecimal')
    return { kind: 'number', isFloat: true };
  if (t === 'boolean' || t === 'Boolean') return { kind: 'boolean' };
  const listMatch = t.match(/List<(\w+)>/);
  if (listMatch) {
    return { kind: 'array', elementType: javaTypeToNode(listMatch[1]), empty: false };
  }
  // Unknown type → treat as a reference (will be resolved or kept as string)
  return { kind: 'string' } as ASTNode;
}

// ─── Go Parser ─────────────────────────────────────────────────

export function parseGoToAST(source: string): ObjectNode {
  const structs = splitGoStructs(source);
  if (structs.length === 0) {
    throw new Error('No Go struct found in input.');
  }
  const nodeMap = new Map<string, ObjectNode>();
  for (const s of structs) {
    const node = parseGoStruct(s);
    nodeMap.set(node.name, node);
  }
  for (const node of nodeMap.values()) {
    for (const field of node.fields) {
      if (field.node.kind === 'string') {
        const resolved = resolveTypeRef(field.node, nodeMap);
        if (resolved) field.node = resolved;
      }
    }
  }
  return nodeMap.values().next().value!;
}

function splitGoStructs(source: string): string[] {
  const results: string[] = [];
  const regex = /type\s+\w+\s+struct\s*\{[^}]*\}/g;
  let match;
  while ((match = regex.exec(source)) !== null) {
    results.push(match[0]);
  }
  if (results.length === 0 && source.trim()) results.push(source);
  return results;
}

function parseGoStruct(s: string): ObjectNode {
  const nameMatch = s.match(/type\s+(\w+)\s+struct/);
  const name = nameMatch ? nameMatch[1] : 'Root';

  const fields: ObjectField[] = [];
  // Match: FieldName Type `json:"..."` or FieldName Type
  const fieldRegex = /^\s+(\w+)\s+([\w\[\].*]+)/gm;
  let m;
  while ((m = fieldRegex.exec(s)) !== null) {
    const fieldName = m[1];
    const goType = m[2].trim();
    // Extract original json key from tag if present
    const lineStr = s.substring(m.index, s.indexOf('\n', m.index));
    const tagMatch = lineStr.match(/`json:"(\w+)"`/);
    const jsonName = tagMatch ? tagMatch[1] : fieldName.charAt(0).toLowerCase() + fieldName.slice(1);
    fields.push({
      name: jsonName,
      node: goTypeToNode(goType),
      nullable: false,
    });
  }
  return { kind: 'object', name, fields };
}

function goTypeToNode(type: string): ASTNode {
  const t = type.trim();
  if (t === 'string') return { kind: 'string' };
  if (t === 'int' || t === 'int32' || t === 'int64') return { kind: 'number', isFloat: false };
  if (t === 'float32' || t === 'float64') return { kind: 'number', isFloat: true };
  if (t === 'bool') return { kind: 'boolean' };
  if (t.startsWith('[]')) {
    return { kind: 'array', elementType: goTypeToNode(t.slice(2)), empty: false };
  }
  if (t === 'interface{}' || t === 'any') return { kind: 'null' };
  return { kind: 'string' } as ASTNode;
}

// ─── Python Parser ─────────────────────────────────────────────

export function parsePythonToAST(source: string): ObjectNode {
  const classes = splitPythonClasses(source);
  if (classes.length === 0) {
    throw new Error('No Python class found in input.');
  }
  const nodeMap = new Map<string, ObjectNode>();
  for (const cls of classes) {
    const node = parsePythonClass(cls);
    nodeMap.set(node.name, node);
  }
  for (const node of nodeMap.values()) {
    for (const field of node.fields) {
      if (field.node.kind === 'string') {
        const resolved = resolveTypeRef(field.node, nodeMap);
        if (resolved) field.node = resolved;
      }
    }
  }
  return nodeMap.values().next().value!;
}

function splitPythonClasses(source: string): string[] {
  const results: string[] = [];
  // Split by class definitions
  const regex = /(?:@\w+\s*\n\s*)*class\s+\w+.*?(?=\n(?:@\w+\s*\n\s*)*class\s|\n*$)/gs;
  let match;
  while ((match = regex.exec(source)) !== null) {
    results.push(match[0]);
  }
  if (results.length === 0 && source.trim()) results.push(source);
  return results;
}

function parsePythonClass(cls: string): ObjectNode {
  const nameMatch = cls.match(/class\s+(\w+)/);
  const name = nameMatch ? nameMatch[1] : 'Root';

  const fields: ObjectField[] = [];
  // Dataclass style: field_name: Type
  const fieldRegex = /^\s+(\w+)\s*:\s*([\w\[\],\s]+)/gm;
  let m;
  while ((m = fieldRegex.exec(cls)) !== null) {
    const fieldName = m[1];
    if (fieldName === 'self' || fieldName === 'def') continue;
    const pyType = m[2].trim().replace(/\s*=.*$/, '');
    fields.push({
      name: fieldName,
      node: pythonTypeToNode(pyType),
      nullable: false,
    });
  }
  // Also try __init__ style: self.field_name = field_name
  if (fields.length === 0) {
    const initRegex = /self\.(\w+)\s*=/gm;
    while ((m = initRegex.exec(cls)) !== null) {
      fields.push({
        name: m[1],
        node: { kind: 'string' },
        nullable: false,
      });
    }
  }
  return { kind: 'object', name, fields };
}

function pythonTypeToNode(type: string): ASTNode {
  const t = type.trim();
  if (t === 'str') return { kind: 'string' };
  if (t === 'int') return { kind: 'number', isFloat: false };
  if (t === 'float') return { kind: 'number', isFloat: true };
  if (t === 'bool') return { kind: 'boolean' };
  if (t === 'None') return { kind: 'null' };
  const listMatch = t.match(/List\[(\w+)\]/);
  if (listMatch) {
    return { kind: 'array', elementType: pythonTypeToNode(listMatch[1]), empty: false };
  }
  const optMatch = t.match(/Optional\[(\w+)\]/);
  if (optMatch) {
    return pythonTypeToNode(optMatch[1]);
  }
  return { kind: 'string' } as ASTNode;
}

// ─── TypeScript Parser ─────────────────────────────────────────

export function parseTypeScriptToAST(source: string): ObjectNode {
  const interfaces = splitTsInterfaces(source);
  if (interfaces.length === 0) {
    throw new Error('No TypeScript interface/type found in input.');
  }
  const nodeMap = new Map<string, ObjectNode>();
  for (const iface of interfaces) {
    const node = parseTsInterface(iface);
    nodeMap.set(node.name, node);
  }
  for (const node of nodeMap.values()) {
    for (const field of node.fields) {
      if (field.node.kind === 'string') {
        const resolved = resolveTypeRef(field.node, nodeMap);
        if (resolved) field.node = resolved;
      }
    }
  }
  return nodeMap.values().next().value!;
}

function splitTsInterfaces(source: string): string[] {
  const results: string[] = [];
  const regex = /(?:export\s+)?interface\s+\w+\s*\{[^}]*\}/g;
  let match;
  while ((match = regex.exec(source)) !== null) {
    results.push(match[0]);
  }
  // Also try type aliases
  if (results.length === 0) {
    const typeRegex = /(?:export\s+)?type\s+\w+\s*=\s*\{[^}]*\}/g;
    while ((match = typeRegex.exec(source)) !== null) {
      results.push(match[0]);
    }
  }
  if (results.length === 0 && source.trim()) results.push(source);
  return results;
}

function parseTsInterface(iface: string): ObjectNode {
  const nameMatch = iface.match(/(?:interface|type)\s+(\w+)/);
  const name = nameMatch ? nameMatch[1] : 'Root';

  const fields: ObjectField[] = [];
  const fieldRegex = /^\s+(\w+)(\??)\s*:\s*(.+?)\s*;?\s*$/gm;
  let m;
  while ((m = fieldRegex.exec(iface)) !== null) {
    const fieldName = m[1];
    const nullable = m[2] === '?';
    const tsType = m[3].trim().replace(/;$/, '');
    fields.push({
      name: fieldName,
      node: tsTypeToNode(tsType),
      nullable,
    });
  }
  return { kind: 'object', name, fields };
}

function tsTypeToNode(type: string): ASTNode {
  const t = type.trim();
  if (t === 'string') return { kind: 'string' };
  if (t === 'number') return { kind: 'number', isFloat: false };
  if (t === 'boolean') return { kind: 'boolean' };
  if (t === 'unknown' || t === 'any' || t === 'null') return { kind: 'null' };
  if (t.endsWith('[]')) {
    return { kind: 'array', elementType: tsTypeToNode(t.slice(0, -2)), empty: false };
  }
  const arrayMatch = t.match(/Array<(.+)>/);
  if (arrayMatch) {
    return { kind: 'array', elementType: tsTypeToNode(arrayMatch[1]), empty: false };
  }
  return { kind: 'string' } as ASTNode;
}

// ─── Kotlin Parser ─────────────────────────────────────────────

export function parseKotlinToAST(source: string): ObjectNode {
  const classes = splitKotlinClasses(source);
  if (classes.length === 0) {
    throw new Error('No Kotlin data class found in input.');
  }
  const nodeMap = new Map<string, ObjectNode>();
  for (const cls of classes) {
    const node = parseKotlinClass(cls);
    nodeMap.set(node.name, node);
  }
  return nodeMap.values().next().value!;
}

function splitKotlinClasses(source: string): string[] {
  const results: string[] = [];
  const regex = /data\s+class\s+\w+\s*\([^)]*\)/g;
  let match;
  while ((match = regex.exec(source)) !== null) {
    results.push(match[0]);
  }
  if (results.length === 0 && source.trim()) results.push(source);
  return results;
}

function parseKotlinClass(cls: string): ObjectNode {
  const nameMatch = cls.match(/class\s+(\w+)/);
  const name = nameMatch ? nameMatch[1] : 'Root';

  const fields: ObjectField[] = [];
  // Match: val fieldName: Type or var fieldName: Type
  const fieldRegex = /(?:val|var)\s+(\w+)\s*:\s*([\w<>?]+)/g;
  let m;
  while ((m = fieldRegex.exec(cls)) !== null) {
    const fieldName = m[1];
    const ktType = m[2].trim();
    const nullable = ktType.endsWith('?');
    fields.push({
      name: fieldName,
      node: kotlinTypeToNode(nullable ? ktType.slice(0, -1) : ktType),
      nullable,
    });
  }
  return { kind: 'object', name, fields };
}

function kotlinTypeToNode(type: string): ASTNode {
  const t = type.trim();
  if (t === 'String') return { kind: 'string' };
  if (t === 'Int' || t === 'Long') return { kind: 'number', isFloat: false };
  if (t === 'Float' || t === 'Double') return { kind: 'number', isFloat: true };
  if (t === 'Boolean') return { kind: 'boolean' };
  if (t === 'Any' || t === 'Any?') return { kind: 'null' };
  const listMatch = t.match(/List<(\w+)>/);
  if (listMatch) {
    return { kind: 'array', elementType: kotlinTypeToNode(listMatch[1]), empty: false };
  }
  return { kind: 'string' } as ASTNode;
}

// ─── Rust Parser ─────────────────────────────────────────────

export function parseRustToAST(source: string): ObjectNode {
  const structs = splitRustStructs(source);
  if (structs.length === 0) {
    throw new Error('No Rust struct found in input.');
  }
  const nodeMap = new Map<string, ObjectNode>();
  for (const s of structs) {
    const node = parseRustStruct(s);
    nodeMap.set(node.name, node);
  }
  return nodeMap.values().next().value!;
}

function splitRustStructs(source: string): string[] {
  const results: string[] = [];
  const regex = /(?:#\[derive\([^)]*\)\]\s*)*(?:pub\s+)?(?:struct|enum)\s+\w+\s*\{[^}]*\}/g;
  let match;
  while ((match = regex.exec(source)) !== null) {
    results.push(match[0]);
  }
  if (results.length === 0 && source.trim()) results.push(source);
  return results;
}

function parseRustStruct(s: string): ObjectNode {
  const nameMatch = s.match(/(?:struct|enum)\s+(\w+)/);
  const name = nameMatch ? nameMatch[1] : 'Root';

  const fields: ObjectField[] = [];
  // Match struct fields -> pub field_name: Type,
  const fieldRegex = /^\s*(?:pub\s+)?(?:r#)?(\w+)\s*:\s*([^,]+),?/gm;
  let m;
  while ((m = fieldRegex.exec(s)) !== null) {
    const fieldName = m[1];
    const rustType = m[2].trim();
    
    // Attempt rudimentary rename logic assuming simple formatting
    let jsonName = fieldName;
    const strBefore = s.substring(0, m.index);
    const lastLines = strBefore.split('\n').filter(l => l.trim().length > 0);
    if (lastLines.length > 0) {
      const lastLine = lastLines[lastLines.length - 1];
      const renameMatch = lastLine.match(/#\[serde\(rename\s*=\s*"([^"]+)"\)\]/);
      if (renameMatch) {
        jsonName = renameMatch[1];
      }
    }

    const isOption = rustType.startsWith('Option<');
    const innerType = isOption ? rustType.substring(7, rustType.length - 1) : rustType;

    fields.push({
      name: jsonName,
      node: rustTypeToNode(innerType),
      nullable: isOption,
    });
  }
  return { kind: 'object', name, fields };
}

function rustTypeToNode(type: string): ASTNode {
  const t = type.trim();
  if (t === 'String' || t === '&str') return { kind: 'string' };
  if (t === 'i32' || t === 'i64' || t === 'u32' || t === 'u64' || t === 'isize' || t === 'usize') return { kind: 'number', isFloat: false };
  if (t === 'f32' || t === 'f64') return { kind: 'number', isFloat: true };
  if (t === 'bool') return { kind: 'boolean' };
  if (t === 'serde_json::Value') return { kind: 'null' };
  const vecMatch = t.match(/Vec<(.+)>/);
  if (vecMatch) {
    return { kind: 'array', elementType: rustTypeToNode(vecMatch[1]), empty: false };
  }
  return { kind: 'string' } as ASTNode;
}

// ─── Shared Helper ─────────────────────────────────────────────

// We store the unresolved type name in a hidden property for resolution
function resolveTypeRef(
  _node: ASTNode,
  _nodeMap: Map<string, ObjectNode>,
): ObjectNode | null {
  // The current approach: unrecognised types are kept as StringNode.
  // Since we can't easily embed metadata in StringNode, we skip cross-ref
  // resolution for now. This works fine for generated code where nested
  // objects are separate definitions.
  return null;
}
